# Site settings
title: ATEC3361 Resources
email: colin@colincampbell.me
description: > # this means to ignore newlines until "baseurl:"
  Resources by Colin Campbell for Arts and Technology 3361 - Internet Studio I
  at the University of Texas at Dallas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: xiroxas
github_repo_uri: colin-c/ATEC3361

# Build settings
markdown: kramdown
